networks:
  ticketz:
  nginx-proxy:

volumes:
  ngx_conf:
  ngx_vhost:
  ngx_html:
  ngx_dhparam:
  ngx_certs:
  ngx_acme:
  redis_data:
  postgres_data:
  minio_data:
  backend_public:
  backend_private:
    
services:

  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: ticketz-nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ngx_conf:/etc/nginx/conf.d
      - ngx_vhost:/etc/nginx/vhost.d
      - ngx_html:/usr/share/nginx/html
      - ngx_dhparam:/etc/nginx/dhparam
      - ngx_certs:/etc/nginx/certs:ro
      - ./confs/nginx-ticketz.conf:/etc/nginx/conf.d/ticketz.conf
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - nginx-proxy

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: ticketz-acme-companion
    restart: always
    depends_on:
      - nginx-proxy
    volumes:
      - ngx_vhost:/etc/nginx/vhost.d
      - ngx_html:/usr/share/nginx/html
      - ngx_dhparam:/etc/nginx/dhparam:ro
      - ngx_certs:/etc/nginx/certs
      - ngx_acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - NGINX_PROXY_CONTAINER=ticketz-nginx-proxy
    networks:
      - nginx-proxy

  backend:
    image: ghcr.io/ticketz-oss/ticketz-backend:pro
    volumes:
      - backend_public:/usr/src/app/public
      - backend_private:/usr/src/app/private
    env_file:
      - .env-backend
    restart: always
    depends_on:
      - acme-companion
      - postgres
      - redis
    networks:
      - ticketz
      - nginx-proxy

  frontend:
    image: ghcr.io/ticketz-oss/ticketz-frontend:pro
    volumes:
      - backend_public:/var/www/backend-public
      - ./confs/frontend-ticketz.d:/etc/nginx/ticketz.d
    env_file:
      - .env-frontend
    restart: always
    depends_on:
      - acme-companion
      - backend
    networks:
      - ticketz
      - nginx-proxy

  postgres:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-ticketz}
      - POSTGRES_DB=${POSTGRES_DB:-ticketz}
      - POSTGRES_HOST_AUTH_METHOD=trust
      - TZ=${TZ:-America/Sao_Paulo}
    expose:
      - 5432
    restart: always
    networks:
      - ticketz

  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes
    expose:
      - 6379
    restart: always
    volumes:
      - redis_data:/data
    networks:
      - ticketz

  watchtower:
    image: containrrr/watchtower
    profiles: ["do-not-start"]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 1800 --cleanup
    restart: unless-stopped

  sidekick:
    image: ghcr.io/ticketz-oss/ticketz-sidekick:latest
    profiles: ["do-not-start"]
    env_file:
      - .env-backend
    restart: unless-stopped
    volumes:
      - backend_public:/backend-public
      - backend_private:/backend-private
      - ./backups:/backups
      - ./retrieve:/retrieve
    depends_on:
      - postgres
    networks:
      - ticketz


  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    restart: always
    env_file:
      - .env-integrations
      - .env-secrets
      - .env-minio
    expose:
      - 9000
      - 9001
    volumes:
      - minio_data:/data
    networks:
      - nginx-proxy
      - ticketz

  # This service just makes sure a bucket with the right policies is created
  createbuckets:
    image: minio/mc
    env_file:
      - .env-integrations
      - .env-secrets
      - .env-minio
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 10;
      /usr/bin/mc config host add minio http://minio:9000 \$\{MINIO_ROOT_USER} \$\{MINIO_ROOT_PASSWORD};
      /usr/bin/mc mb minio/typebot;
      /usr/bin/mc anonymous set public minio/typebot/public;
      exit 0;
      "
    networks:
      - nginx-proxy

  typebot-builder:
    image: baptistearno/typebot-builder:latest
    restart: always
    depends_on:
      - postgres
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file:
      - .env-integrations
      - .env-secrets
      - .env-typebot-common
      - .env-typebot-builder
    networks:
      - ticketz
      - nginx-proxy

  typebot-viewer:
    image: baptistearno/typebot-viewer:latest
    restart: always
    env_file:
      - .env-integrations
      - .env-secrets
      - .env-typebot-common
      - .env-typebot-viewer
    networks:
      - ticketz
      - nginx-proxy
